export const MOVIE_PLACEHOLDERS = [
  { id: '%movie_id%', display: 'ID фильма' },
  { id: '%title%', display: 'Название фильма' },
  { id: '%orig_title%', display: 'Оригинальное название фильма' },
  { id: '%translate%', display: 'Озвучка' },
  { id: '%translate_id%', display: 'ID озвучки' },
  { id: '%quality%', display: 'Качество видео' },
  { id: '%subtitle_code%', display: 'Код субтитров' },
  { id: '%subtitle_lang%', display: 'Язык субтитров' },
  { id: '%data%', display: 'Дата' },
  { id: '%time%', display: 'Время' },
];

export const SERIES_PLACEHOLDERS = [
  { id: '%n%', display: 'Номер файла' },
  { id: '%movie_id%', display: 'ID фильма' },
  { id: '%title%', display: 'Название фильма' },
  { id: '%orig_title%', display: 'Оригинальное название фильма' },
  { id: '%translate%', display: 'Озвучка' },
  { id: '%translate_id%', display: 'ID озвучки' },
  { id: '%episode%', display: 'Эпизод' },
  { id: '%episode_id%', display: 'ID эпизода' },
  { id: '%season%', display: 'Сезон' },
  { id: '%season_id%', display: 'ID сезона' },
  { id: '%quality%', display: 'Качество видео' },
  { id: '%subtitle_code%', display: 'Код субтитров' },
  { id: '%subtitle_lang%', display: 'Язык субтитров' },
  { id: '%data%', display: 'Дата' },
  { id: '%time%', display: 'Время' },
];

export const SERIES_READY_TEMPLATES = [
  [
    '%n%',
    ') ',
    '%orig_title%',
    '[',
    '%translate%',
    '] (',
    '%season%',
    ') (',
    '%episode%',
    ')',
  ],
  [
    '%orig_title%',
    '(',
    '%translate%',
    ')_S-',
    '%season_id%',
    '_E-',
    '%episode_id%',
    '_[',
    '%quality%',
    ']',
  ],
];

export const MOVIE_READY_TEMPLATES = [
  [
    '%n%',
    ') ',
    '%orig_title%',
    '[',
    '%translate%',
    '] (',
    '%season%',
    ') (',
    '%episode%',
    ')',
  ],
  [
    '%orig_title%',
    '(',
    '%translate%',
    ')_S-',
    '%season_id%',
    '_E-',
    '%episode_id%',
    '_[',
    '%quality%',
    ']',
  ],
];

export const MOVIE_PREVIEW = [
  {
    label: 'Обычный фильм, без субтитров.',
    value: {
      '%n%': '1',
      '%movie_id%': '768',
      '%title%': 'Как приручить дракона',
      '%orig_title%': 'How to Train Your Dragon',
      '%translate%': 'Дубляж',
      '%translate_id%': '56',
      '%episode%': undefined,
      '%episode_id%': undefined,
      '%season%': undefined,
      '%season_id%': undefined,
      '%quality%': '1080p Ultra',
      '%subtitle_code%': undefined,
      '%subtitle_lang%': undefined,
      '%data%': '',
      '%time%': '',
    },
  },
  {
    label: 'Обычный фильм, с субтитрами.',
    value: {
      '%n%': '1',
      '%movie_id%': '1043',
      '%title%': 'Гарри Поттер и философский камень',
      '%orig_title%': "Harry Potter and the Sorcerer's Stone",
      '%translate%': 'Дубляж',
      '%translate_id%': '56',
      '%episode%': undefined,
      '%episode_id%': undefined,
      '%season%': undefined,
      '%season_id%': undefined,
      '%quality%': '1080p Ultra',
      '%subtitle_code%': 'ru',
      '%subtitle_lang%': 'Русский',
      '%data%': '',
      '%time%': '',
    },
  },
  {
    label: 'Нет оригинального названия.',
    value: {
      '%n%': '1',
      '%movie_id%': '12719',
      '%title%': 'Rammstein in Amerika',
      '%orig_title%': '',
      '%translate%': 'Студия Омикрон',
      '%translate_id%': '267',
      '%episode%': undefined,
      '%episode_id%': undefined,
      '%season%': undefined,
      '%season_id%': undefined,
      '%quality%': '1080p Ultra',
      '%subtitle_code%': undefined,
      '%subtitle_lang%': undefined,
      '%data%': '',
      '%time%': '',
    },
  },
  {
    label: 'В названии есть спец. символы которые будут обрезаны.',
    value: {
      '%n%': '1',
      '%movie_id%': '5005',
      '%title%': 'З/Л/О: Новый вирус',
      '%orig_title%': 'V/H/S: Viral',
      '%translate%': 'Дубляж',
      '%translate_id%': '56',
      '%episode%': undefined,
      '%episode_id%': undefined,
      '%season%': undefined,
      '%season_id%': undefined,
      '%quality%': '1080p Ultra',
      '%subtitle_code%': undefined,
      '%subtitle_lang%': undefined,
      '%data%': '',
      '%time%': '',
    },
  },
  {
    label: 'Озвучка режиссёрская версия.',
    value: {
      '%n%': '1',
      '%movie_id%': '969',
      '%title%': 'Властелин колец: Возвращение Короля',
      '%orig_title%': 'The Lord of the Rings: The Return of the King',
      '%translate%': 'Дубляж',
      '%translate_id%': '56',
      '%episode%': undefined,
      '%episode_id%': undefined,
      '%season%': undefined,
      '%season_id%': undefined,
      '%quality%': '1080p Ultra',
      '%subtitle_code%': undefined,
      '%subtitle_lang%': undefined,
      '%data%': '',
      '%time%': '',
    },
  },
];

export const SERIES_PREVIEW = [
  {
    label: 'Обычный сериал, без субтитров.',
    value: {
      '%n%': '1',
      '%movie_id%': '45',
      '%title%': 'Игра престолов',
      '%orig_title%': 'Game of Thrones',
      '%translate%': 'HDrezka Studio',
      '%translate_id%': '111',
      '%episode%': 'Серия 1',
      '%episode_id%': '1',
      '%season%': 'Сезон 1',
      '%season_id%': '1',
      '%quality%': '1080p Ultra',
      '%subtitle_code%': undefined,
      '%subtitle_lang%': undefined,
      '%data%': '',
      '%time%': '',
    },
  },
  {
    label: 'Обычный сериал, с субтитрами.',
    value: {
      '%n%': '2',
      '%movie_id%': '646',
      '%title%': 'Во все тяжкие',
      '%orig_title%': 'Breaking Bad',
      '%translate%': 'Оригинал (+субтитры)',
      '%translate_id%': '238',
      '%episode%': 'Серия 2',
      '%episode_id%': '2',
      '%season%': 'Сезон 1',
      '%season_id%': '1',
      '%quality%': '1080p Ultra',
      '%subtitle_code%': 'ru',
      '%subtitle_lang%': 'Русский',
      '%data%': '',
      '%time%': '',
    },
  },
  {
    label: 'Нет оригинального названия.',
    value: {
      '%n%': '3',
      '%movie_id%': '46346',
      '%title%': 'Halo',
      '%orig_title%': '',
      '%translate%': 'Амедиа (Amedia)',
      '%translate_id%': '12',
      '%episode%': 'Серия 3',
      '%episode_id%': '3',
      '%season%': 'Сезон 1',
      '%season_id%': '1',
      '%quality%': '1080p Ultra',
      '%subtitle_code%': undefined,
      '%subtitle_lang%': undefined,
      '%data%': '',
      '%time%': '',
    },
  },
  {
    label: 'В названии есть спец. символы которые будут обрезаны.',
    value: {
      '%n%': '4',
      '%movie_id%': '10827',
      '%title%':
        'Звёздная принцесса и силы зла / Стар против Сил Зла / Звезда против Сил Зла',
      '%orig_title%': 'Star vs. The Forces of Evil',
      '%translate%': 'HDrezka Studio',
      '%translate_id%': '111',
      '%episode%': 'Серия 4',
      '%episode_id%': '4',
      '%season%': 'Сезон 1',
      '%season_id%': '1',
      '%quality%': '1080p Ultra',
      '%subtitle_code%': undefined,
      '%subtitle_lang%': undefined,
      '%data%': '',
      '%time%': '',
    },
  },
  {
    label: 'Необычное название серий.',
    value: {
      '%n%': '5',
      '%movie_id%': '34965',
      '%title%': 'Червяк из будущего',
      '%orig_title%': 'Future-Worm!',
      '%translate%': 'Дубляж',
      '%translate_id%': '56',
      '%episode%': 'Special 5',
      '%episode_id%': '5',
      '%season%': 'Сезон 0',
      '%season_id%': '0',
      '%quality%': '1080p Ultra',
      '%subtitle_code%': undefined,
      '%subtitle_lang%': undefined,
      '%data%': '',
      '%time%': '',
    },
  },
];
